In [1]:
import torch
torch.cuda.is_available()

False

In [3]:
import pandas as pd
acc_x = pd.read_csv(r'D:\pytorch_tutorials\UCI-HAR Dataset\train\Inertial Signals\body_acc_x_train.txt',header = None, sep = r'\s+').to_numpy()
print(acc_x.shape)

(7352, 128)


In [4]:
acc_y = pd.read_csv(r'D:\pytorch_tutorials\UCI-HAR Dataset\train\Inertial Signals\body_acc_y_train.txt',header = None,sep = r'\s+').to_numpy()
print(acc_y.shape)

(7352, 128)


In [5]:
acc_z = pd.read_csv(r'D:\pytorch_tutorials\UCI-HAR Dataset\train\Inertial Signals\body_acc_z_train.txt',header = None,sep = r'\s+').to_numpy()
print(acc_z.shape)

(7352, 128)


In [6]:
gyro_x = pd.read_csv(r'D:\pytorch_tutorials\UCI-HAR Dataset\train\Inertial Signals\body_gyro_x_train.txt',header = None,sep = r'\s+').to_numpy()
print(gyro_x.shape)

(7352, 128)


In [7]:
gyro_y = pd.read_csv(r'D:\pytorch_tutorials\UCI-HAR Dataset\train\Inertial Signals\body_gyro_y_train.txt',header = None,sep = r'\s+').to_numpy()
print(gyro_y.shape)

(7352, 128)


In [8]:
gyro_z = pd.read_csv(r'D:\pytorch_tutorials\UCI-HAR Dataset\train\Inertial Signals\body_gyro_z_train.txt',header = None,sep = r'\s+').to_numpy()
print(gyro_z.shape)

(7352, 128)


In [9]:
tot_x = pd.read_csv(r'D:\pytorch_tutorials\UCI-HAR Dataset\train\Inertial Signals\total_acc_x_train.txt',header = None,sep = r'\s+').to_numpy()
print(tot_x.shape)

(7352, 128)


In [10]:
tot_y = pd.read_csv(r'D:\pytorch_tutorials\UCI-HAR Dataset\train\Inertial Signals\total_acc_y_train.txt',header = None,sep = r'\s+').to_numpy()
print(tot_y.shape)

(7352, 128)


In [11]:
tot_z = pd.read_csv(r'D:\pytorch_tutorials\UCI-HAR Dataset\train\Inertial Signals\total_acc_z_train.txt',header = None,sep = r'\s+').to_numpy()
print(tot_z.shape)

(7352, 128)


In [12]:
import numpy as np
x_train = np.dstack([acc_x,acc_y,acc_z,gyro_x,gyro_y,gyro_z,tot_x,tot_y,tot_z])

In [13]:
x_train.shape

(7352, 128, 9)

In [14]:
print(x_train[0].shape)

(128, 9)


In [15]:
print(x_train[0][0])

[ 1.808515e-04  1.076681e-02  5.556068e-02  3.019122e-02  6.601362e-02
  2.285864e-02  1.012817e+00 -1.232167e-01  1.029341e-01]


In [16]:
import pandas as pd
y_train = pd.read_csv(r"D:\pytorch_tutorials\UCI-HAR Dataset\train\y_train.txt",header = None).to_numpy()
y_test = pd.read_csv(r"D:\pytorch_tutorials\UCI-HAR Dataset\test\y_test.txt",header = None).to_numpy()

In [17]:
print(y_train.shape)
print(y_test.shape)

(7352, 1)
(2947, 1)


In [18]:
y_train

array([[5],
       [5],
       [5],
       ...,
       [2],
       [2],
       [2]], shape=(7352, 1))

In [19]:
y_train = y_train -1
y_test = y_test -1

In [20]:
y_train

array([[4],
       [4],
       [4],
       ...,
       [1],
       [1],
       [1]], shape=(7352, 1))

In [21]:
test_acc_x = pd.read_csv(r"D:\pytorch_tutorials\UCI-HAR Dataset\test\Inertial Signals\body_acc_x_test.txt",header = None,sep = r'\s+').to_numpy()
test_acc_y = pd.read_csv(r"D:\pytorch_tutorials\UCI-HAR Dataset\test\Inertial Signals\body_acc_y_test.txt",header = None,sep = r'\s+').to_numpy()
test_acc_z = pd.read_csv(r"D:\pytorch_tutorials\UCI-HAR Dataset\test\Inertial Signals\body_acc_z_test.txt",header = None,sep = r'\s+').to_numpy()
test_gyro_x = pd.read_csv(r"D:\pytorch_tutorials\UCI-HAR Dataset\test\Inertial Signals\body_gyro_x_test.txt",header = None,sep = r"\s+").to_numpy()
test_gyro_y = pd.read_csv(r"D:\pytorch_tutorials\UCI-HAR Dataset\test\Inertial Signals\body_gyro_y_test.txt",header = None,sep = r"\s+").to_numpy()
test_gyro_z = pd.read_csv(r"D:\pytorch_tutorials\UCI-HAR Dataset\test\Inertial Signals\body_gyro_z_test.txt",header = None,sep = r"\s+").to_numpy()
tot_test_x = pd.read_csv(r"D:\pytorch_tutorials\UCI-HAR Dataset\test\Inertial Signals\total_acc_x_test.txt",header = None,sep = r"\s+").to_numpy()
tot_test_y = pd.read_csv(r"D:\pytorch_tutorials\UCI-HAR Dataset\test\Inertial Signals\total_acc_y_test.txt",header = None,sep = r"\s+").to_numpy()
tot_test_z = pd.read_csv(r"D:\pytorch_tutorials\UCI-HAR Dataset\test\Inertial Signals\total_acc_z_test.txt",header = None,sep = r"\s+").to_numpy()
x_test = np.dstack([test_acc_x,test_acc_y,test_acc_z,test_gyro_x,test_gyro_y,test_gyro_z,tot_test_x,tot_test_y,tot_test_z])
x_test.shape

(2947, 128, 9)

In [25]:
x_test[0].shape
sample = x_train[0]
df = pd.DataFrame(
    sample,
    columns = [
        'body_acc_x',
        'body_acc_y',
        'body_acc_z',
        'body_gyro_x',
        'body_gyro_y',
        'body_gyro_z',
        'total_acc_x',
        'total_acc_y',
        'total_acc_z'
    ]
)
df.to_csv("sample.csv",index = False)

In [610]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(7352, 128, 9)
(7352, 1)
(2947, 128, 9)
(2947, 1)


In [611]:
x_train = torch.tensor(x_train,dtype = torch.float32)
x_test = torch.tensor(x_test,dtype = torch.float32)
y_train = torch.tensor(y_train,dtype = torch.long)
y_test = torch.tensor(y_test,dtype = torch.long)

In [612]:
y_train = y_train.squeeze()
y_test = y_test.squeeze()

In [613]:
y_train.shape

torch.Size([7352])

In [614]:
y_test.shape

torch.Size([2947])

In [615]:
x_test.shape

torch.Size([2947, 128, 9])

In [616]:
x_train.shape

torch.Size([7352, 128, 9])

In [617]:
import torch.nn as nn
class HAR_LSTM(nn.Module):
    def __init__(self):
        super().__init__()
        self.lstm = nn.LSTM(
            input_size = 9,
            hidden_size = 256,
            num_layers = 2,
            batch_first = True,
            dropout = 0.1
        )
        self.dropout = nn.Dropout(0.1)
        self.fc = nn.Linear(256,6)
    def forward(self,x):
        output,(hidden,cell) = self.lstm(x)
        hidden = self.dropout(hidden[-1])
        output = self.fc(hidden)
        return output
        

In [618]:
from torch.utils.data import TensorDataset,DataLoader
train_dataset = TensorDataset(x_train,y_train)
test_dataset = TensorDataset(x_test,y_test)

In [619]:
train_dataset[0]

(tensor([[ 1.8085e-04,  1.0767e-02,  5.5561e-02,  ...,  1.0128e+00,
          -1.2322e-01,  1.0293e-01],
         [ 1.0139e-02,  6.5795e-03,  5.5125e-02,  ...,  1.0228e+00,
          -1.2688e-01,  1.0569e-01],
         [ 9.2756e-03,  8.9289e-03,  4.8405e-02,  ...,  1.0220e+00,
          -1.2400e-01,  1.0210e-01],
         ...,
         [-1.1475e-03,  1.7144e-04,  2.6479e-03,  ...,  1.0184e+00,
          -1.2407e-01,  1.0039e-01],
         [-2.2227e-04,  1.5742e-03,  2.3811e-03,  ...,  1.0194e+00,
          -1.2275e-01,  9.9874e-02],
         [ 1.5755e-03,  3.0702e-03, -2.2698e-03,  ...,  1.0212e+00,
          -1.2133e-01,  9.4987e-02]]),
 tensor(4))

In [620]:

train_loader = DataLoader(train_dataset,batch_size = 32,shuffle = True)
test_loader = DataLoader(test_dataset,batch_size = 32,shuffle = False)

In [621]:
for x_batch,y_batch in train_loader:
    print(x_batch.shape)
    print(y_batch.shape)
    break

torch.Size([32, 128, 9])
torch.Size([32])


In [622]:
model = HAR_LSTM()

In [623]:
model

HAR_LSTM(
  (lstm): LSTM(9, 256, num_layers=2, batch_first=True, dropout=0.1)
  (dropout): Dropout(p=0.1, inplace=False)
  (fc): Linear(in_features=256, out_features=6, bias=True)
)

In [624]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda')

In [625]:
model = model.to(device)

In [626]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(),lr =0.001)

In [627]:
epochs = 70
for epoch in range(epochs):
    model.train()
    running_loss = 0.0
    for x_batch,y_batch in train_loader:
        x_batch = x_batch.to(device)
        y_batch = y_batch.to(device)
        outputs = model(x_batch)
        loss = criterion(outputs,y_batch)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        running_loss +=loss.item()
    print(f"Epoch {epoch+1}/{epochs}, Loss: {running_loss/len(train_loader):.4f}")

Epoch 1/70, Loss: 1.6538
Epoch 2/70, Loss: 1.7535
Epoch 3/70, Loss: 1.8015
Epoch 4/70, Loss: 1.7403
Epoch 5/70, Loss: 1.4025
Epoch 6/70, Loss: 1.2835
Epoch 7/70, Loss: 1.2109
Epoch 8/70, Loss: 0.9064
Epoch 9/70, Loss: 1.0037
Epoch 10/70, Loss: 0.7064
Epoch 11/70, Loss: 0.5688
Epoch 12/70, Loss: 0.3144
Epoch 13/70, Loss: 0.2175
Epoch 14/70, Loss: 0.4488
Epoch 15/70, Loss: 0.2135
Epoch 16/70, Loss: 0.1540
Epoch 17/70, Loss: 0.1530
Epoch 18/70, Loss: 0.1355
Epoch 19/70, Loss: 0.1337
Epoch 20/70, Loss: 0.1368
Epoch 21/70, Loss: 0.1449
Epoch 22/70, Loss: 0.1323
Epoch 23/70, Loss: 0.1272
Epoch 24/70, Loss: 0.1317
Epoch 25/70, Loss: 0.1205
Epoch 26/70, Loss: 0.1180
Epoch 27/70, Loss: 0.1586
Epoch 28/70, Loss: 0.1254
Epoch 29/70, Loss: 0.1381
Epoch 30/70, Loss: 0.1513
Epoch 31/70, Loss: 0.1237
Epoch 32/70, Loss: 0.1210
Epoch 33/70, Loss: 0.1189
Epoch 34/70, Loss: 0.1251
Epoch 35/70, Loss: 0.1070
Epoch 36/70, Loss: 0.1144
Epoch 37/70, Loss: 0.1099
Epoch 38/70, Loss: 0.1201
Epoch 39/70, Loss: 0.

In [628]:
model.eval()
all_predictions = []
all_labels = []
with torch.no_grad():
    for x_batch,y_batch in test_loader:
        x_batch = x_batch.to(device)
        y_batch = y_batch.to(device)
        outputs = model(x_batch)
        _,predicted = torch.max(outputs,1)
        all_predictions.extend(predicted.cpu().numpy())
        all_labels.extend(y_batch.cpu().numpy())

In [629]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
accuracy = accuracy_score(all_labels,all_predictions)
print("Accuracy: {:.4f}".format(accuracy))

Accuracy: 0.9274


In [630]:
print("Classification Report: ",classification_report(all_labels,all_predictions))

Classification Report:                precision    recall  f1-score   support

           0       1.00      0.99      0.99       496
           1       0.94      0.95      0.95       471
           2       0.95      0.99      0.97       420
           3       0.85      0.82      0.84       491
           4       0.84      0.87      0.85       532
           5       1.00      0.95      0.97       537

    accuracy                           0.93      2947
   macro avg       0.93      0.93      0.93      2947
weighted avg       0.93      0.93      0.93      2947



In [631]:
print("Confusion matrix: \n",confusion_matrix(all_labels,all_predictions))

Confusion matrix: 
 [[493   0   3   0   0   0]
 [  1 449  21   0   0   0]
 [  1   2 417   0   0   0]
 [  0   0   0 403  88   0]
 [  0   0   0  71 461   0]
 [  0  27   0   0   0 510]]


In [632]:
torch.save(model.state_dict(),r"D:\pytorch_tutorials\models\lstm_har_model.pth")